# Generated by Django 4.1.2 on 2023-02-09 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_contacts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='contacts',
        ),
    ]
