# Generated by Django 4.1.2 on 2022-11-24 13:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('name', models.CharField(max_length=2000, verbose_name='Nombre del servicio')),
                ('currency', models.IntegerField(choices=[(0, 'USD'), (1, 'EUR')], default=0, verbose_name='Divisa')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='Fecha de cobro')),
                ('amount', models.FloatField(default=0, verbose_name='Monto')),
                ('files', models.ManyToManyField(blank=True, null=True, related_name='files', to='files.mediafile', verbose_name='Archivos')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Responsable')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
