# Generated by Django 4.1.2 on 2022-12-14 12:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('files', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('name', models.CharField(max_length=1000, verbose_name='Nombre del servicio')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='service',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='service',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='service',
            name='files',
        ),
        migrations.RemoveField(
            model_name='service',
            name='payment_date',
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=1000, verbose_name='Nombre del servicio'),
        ),
        migrations.AlterField(
            model_name='service',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service', to=settings.AUTH_USER_MODEL, verbose_name='Responsable'),
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('title', models.CharField(max_length=1000, verbose_name='Título del grupo')),
                ('currency', models.IntegerField(choices=[(0, 'USD'), (1, 'EUR')], default=0, verbose_name='Divisa')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='Fecha de cobro')),
                ('amount', models.FloatField(default=0, verbose_name='Monto')),
                ('files', models.ManyToManyField(blank=True, related_name='files', to='files.mediafile', verbose_name='Archivos')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_groups', to=settings.AUTH_USER_MODEL, verbose_name='Responsable')),
                ('users', models.ManyToManyField(blank=True, related_name='assoc_groups', to=settings.AUTH_USER_MODEL, verbose_name='Usuarios asociados')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='service',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='services', to='services.category', verbose_name='Categorías'),
        ),
    ]
