# Generated by Django 4.1.2 on 2022-12-15 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_group_service_alter_group_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='group_image',
            field=models.ImageField(blank=True, null=True, upload_to='group/', verbose_name='Imagen del grupo'),
        ),
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='service/', verbose_name='Imagen del servicio'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=1000, verbose_name='Nombre'),
        ),
    ]
